export enum Genre {
    POP = 'pop',
    ROCK = 'rock',
    HIP_HOP = 'hip_hop',
    RAP = 'rap',
    ELECTRONIC = 'electronic',
    TECHNO = 'techno',
    HOUSE = 'house',
    JAZZ = 'jazz',
    BLUES = 'blues',
    CLASSICAL = 'classical',
    INDIE = 'indie',
    METAL = 'metal',
    PUNK = 'punk',
    FOLK = 'folk',
    COUNTRY = 'country',
    RNB = 'rnb',
    REGGAE = 'reggae',
    K_POP = 'k_pop',
    LATIN = 'latin',
    SOUL = 'soul',
    ALTERNATIVE = 'alternative'
}
